### Test: Auth Login
# Trả về chuỗi JWT Token và thông tin User cơ bản
# @name login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@mazak.com.vn",
  "password": "SuperSecurePassword2026"
}

###

### Test: Lấy thông tin bản thân (Profile)
# Yêu cầu truyền Authorization Bearer lấy được từ API Login ở trên
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer {{login.response.body.data.accessToken}}

###

### Test: Cấp lại Token (Refresh Token)
# Đổi Refresh Token lấy một cặp Access Token & Refresh Token mới
# @name refresh
POST http://localhost:3000/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{login.response.body.data.refreshToken}}"
}

###

### Test: Đăng xuất (Logout)
# Sẽ xóa Refresh Token của user trong database
POST http://localhost:3000/api/v1/auth/logout
Authorization: Bearer {{login.response.body.data.accessToken}}

###

### Test: Báo lỗi Validation
# Sẽ trả về lỗi nếu thiếu trường password và sai định dạng email
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "sai-dinh-dang-email"
}

###

### Test: Báo lỗi Guard Unauthorized
# Sẽ trả về lỗi 401 do không có token truyền lên
GET http://localhost:3000/api/v1/auth/me
