-- AlterTable
ALTER TABLE "ContactSetting" ADD COLUMN IF NOT EXISTS "hotline" TEXT NOT NULL DEFAULT '0374 864 110',
ADD COLUMN IF NOT EXISTS "zalo" TEXT NOT NULL DEFAULT '0374 864 110',
ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL DEFAULT 'info@kiendinhecm.com',
ADD COLUMN IF NOT EXISTS "address" TEXT,
ADD COLUMN IF NOT EXISTS "workingHours" TEXT;

-- DropTable
DROP TABLE IF EXISTS "ContactChannel";
